import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useEffect } from "react";
import { useTheme } from "@mui/material";
import AlertDialog from "@/components/alert";
import Showcase from "@/components/home/showcase";
import Advertise from "@/components/home/advertise";
import OurCourses from "@/components/home/ourCourses";
import Companies from "@/components/home/companies";
import { courses } from "@/data/courses";
import Student from "@/components/home/students";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  let theme = useTheme();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Showcase />
        <Advertise />
        <OurCourses />
        <Student />
      </main>
    </>
  );
}
