import Module from "@/components/module";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Module 1</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Module />
      </main>
    </>
  );
}
